nameOverride: "devops-task"
fullnameOverride: "devops-task"

replicaCount: 1
image:
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
