namespace: dev-ns

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: devops-task-services
    version: 0.1.0
    releaseName: order-service
    valuesFile: orders.yml
    namespace: dev-ns

secretGenerator:
  - name: order-service-secret
    envs:
      - orders.env
